#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Which
Version  : 1.22
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.22.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/File-Which-1.22.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-which-perl/libfile-which-perl_1.21-1.debian.tar.xz
Summary  : 'Perl implementation of the which utility as an API'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-File-Which-man

%description
NAME
File::Which - Perl implementation of the which utility as an API
VERSION
version 1.22

%package man
Summary: man components for the perl-File-Which package.
Group: Default

%description man
man components for the perl-File-Which package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n File-Which-1.22
mkdir -p %{_topdir}/BUILD/File-Which-1.22/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/File-Which-1.22/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/File/Which.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/File::Which.3
